# Generated by Django 5.1.2 on 2024-12-01 00:14

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_socio', models.CharField(max_length=10)),
                ('fecha_emision', models.DateField(default=datetime.date.today)),
                ('tarjeta_activa', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('apertura_lunes_viernes', models.TimeField(blank=True, null=True)),
                ('cierre_lunes_viernes', models.TimeField(blank=True, null=True)),
                ('apertura_sabado', models.TimeField(blank=True, null=True)),
                ('cierre_sabado', models.TimeField(blank=True, null=True)),
                ('apertura_domingo_festivo', models.TimeField(blank=True, null=True)),
                ('cierre_domingo_festivo', models.TimeField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator()])),
                ('descripcion', models.TextField()),
                ('premium', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='negocios/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negocios', to='core.categoria')),
                ('oferta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negocios', to='core.oferta')),
            ],
        ),
    ]
