# Generated by Django 5.1.2 on 2024-12-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
