# Generated by Django 5.1.1 on 2024-10-13 20:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_negocio_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="negocio",
            name="imagen",
        ),
    ]
