# Generated by Django 5.1.1 on 2024-10-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_negocio_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="negocio",
            name="imagen",
            field=models.ImageField(
                default="negocios/default.jpg", upload_to="negocios/"
            ),
        ),
    ]
