# Generated by Django 5.1.1 on 2024-10-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_negocio_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="negocio",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="negocios/"),
        ),
    ]
