# Generated by Django 5.1.1 on 2024-11-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_categoria_negocio_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="negocio",
            name="premium",
            field=models.BooleanField(default=False),
        ),
    ]
