# Generated by Django 5.1.1 on 2024-11-02 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_negocio_premium"),
    ]

    operations = [
        migrations.CreateModel(
            name="Oferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "precio",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("activa", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="negocio",
            name="oferta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="negocios",
                to="core.oferta",
            ),
        ),
    ]
