# Generated by Django 5.1.1 on 2024-11-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_oferta_negocio_oferta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="negocio",
            name="horario",
        ),
        migrations.AddField(
            model_name="negocio",
            name="apertura_domingo_festivo",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="negocio",
            name="apertura_lunes_viernes",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="negocio",
            name="apertura_sabado",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="negocio",
            name="cierre_domingo_festivo",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="negocio",
            name="cierre_lunes_viernes",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="negocio",
            name="cierre_sabado",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
